
import './globals.css'
import Darkmode from '@/components/layout/Darkmode'
import Navbar from '@/components/layout/Navbar'
import SessionProvider from '@/components/logic/SessionProvider'
import Toast from '@/components/layout/Toast'
import Footer from '@/components/layout/Footer'



export const metadata = {
  title: 'Spirited Score',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
        <Darkmode>
        <SessionProvider>
          <Toast/>
          <Navbar/>
        <main className='min-h-screen'>
          {children}
          </main>
        <Footer/>
          </SessionProvider>
        </Darkmode>
  )
}
