
import './globals.css'
import Darkmode from '@/components/layout/Darkmode'
import Navbar from '@/components/layout/Navbar'
import SessionProvider from '@/components/logic/SessionProvider'
import Toast from '@/components/layout/Toast'



export const metadata = {
  title: 'Spirited Score',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
        <Darkmode>
        <SessionProvider>
          <Toast/>
          <Navbar/>
        <main className=" bg-white dark:bg-gray-800 text-black dark:text-white min-h-screen ">
          {children}
          </main>
          </SessionProvider>
        </Darkmode>
  )
}
